### ISSUE TITLE
Review and merge outstanding scijava-ops-related PRs

### ISSUE THREAD

**Issue by ctrueden** [scijava/scijava#75]
There is a line of PRs, each of which is based on the previous one, which need sequential review:

* [x] scijava/incubator#35 (reviewed+merged, with changes on top the full chain in progress)
* [x] scijava/incubator#28 (reviewed, might need rebase before merge)
* [x] scijava/incubator#31
* [x] scijava/scijava-packages-rules#1 (review and merge, then cut a release)
* [x] scijava/incubator#39
* [x] scijava/incubator#40
* [x] scijava/incubator#41
* [x] scijava/incubator#46
* [x] scijava/incubator#47
* [x] scijava/incubator#42
* [x] scijava/incubator#43
* [x] scijava/incubator#44
* [x] scijava/incubator#48
* [x] scijava/incubator#49
* [x] scijava/incubator#51
* [x] scijava/incubator#50
* [x] scijava/incubator#52
* [x] scijava/incubator#53
* [x] scijava/incubator#54
* [x] scijava/incubator#56
* [x] scijava/incubator#57
* [x] scijava/incubator#64
* [x] scijava/incubator#58
* [x] scijava/incubator#55
* [ ] <s>scijava/incubator#45 - should be rebased to find commits</s>

Each PR will be rebased against the latest main branch, with critical problems fixed immediately, then merged as is. New PRs will emerge on top of the full chain addressing all the points that arose during each review. @gselzer will make these changes on top of the full chain.

**Comment by ctrueden** [comment]
I will work on reviewing scijava/incubator#28 and scijava/incubator#31 ASAP. When @gselzer and I meet next, we will work on scijava/scijava-packages-rules#1 together, so that we can cover how to cut releases.

**Comment by ctrueden** [comment]
@hinerm @gselzer Good news: copying the `tube.tif` expected image from imagej-ops to incubator *does* fix the failing `TubenessTest` on my Linux system. So I integrated it into the "Turn on ImageJ Ops2 tests" as 91d3044f6db2de3ff696138f17206001d1bca84d. There is still at least one other failing test for me, though; will keep you posted.

**Comment by ctrueden** [comment]
@hinerm Can this issue be closed as completed now, at long last? 🥲
